{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.opal",
    "module": "opal-core",
    "version": "3.2.6-2025_update20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantMavenApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.8-android"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "24.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "opal-core-3.2.6-2025_update20.aar",
          "url": "opal-core-3.2.6-2025_update20.aar",
          "size": 226292,
          "sha512": "dd25a30b6b72f0322f728b2ee967da82abd5adaabfb67cfbfac74faa7f5a5f0a53b5bbbc4ce5f8a5ccfb8db9af2024ab5fc268ba01db1b7fbd9786bece922137",
          "sha256": "1178453dc9da1c01981e0d83ad0fb242d7717df9aadb5e9f779c3912c5013783",
          "sha1": "77952a94d370a7e1447921cf90a9d101d7a3d6a1",
          "md5": "e18a60833f26b6d1e3c649c65f528154"
        }
      ]
    },
    {
      "name": "releaseVariantMavenRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.8-android"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "24.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "opal-core-3.2.6-2025_update20.aar",
          "url": "opal-core-3.2.6-2025_update20.aar",
          "size": 226292,
          "sha512": "dd25a30b6b72f0322f728b2ee967da82abd5adaabfb67cfbfac74faa7f5a5f0a53b5bbbc4ce5f8a5ccfb8db9af2024ab5fc268ba01db1b7fbd9786bece922137",
          "sha256": "1178453dc9da1c01981e0d83ad0fb242d7717df9aadb5e9f779c3912c5013783",
          "sha1": "77952a94d370a7e1447921cf90a9d101d7a3d6a1",
          "md5": "e18a60833f26b6d1e3c649c65f528154"
        }
      ]
    }
  ]
}
