{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.opal",
    "module": "opal-push-fcm",
    "version": "3.2.6-2025_update27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantMavenApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "opal-push-fcm-3.2.6-2025_update27.aar",
          "url": "opal-push-fcm-3.2.6-2025_update27.aar",
          "size": 149494,
          "sha512": "18cc5370ffa8f47369afbc945c88e0b75a41134396dcf2e5fb193e794d98da77c833b2f3168d9d2a6a7b45188e2de393148c0cc931b61fd3020a50aebda7f8bf",
          "sha256": "1aeb5ff98acee6f757d8d6f60cd0e0c5c4fb9723a6bf8f11b937eaa1a5026a28",
          "sha1": "3324bf18a38b83a649cfa45f86bffec2bdd78e57",
          "md5": "8571b19c0b8a5cf46f993b4d83d2f217"
        }
      ]
    },
    {
      "name": "releaseVariantMavenRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "opal-push-fcm-3.2.6-2025_update27.aar",
          "url": "opal-push-fcm-3.2.6-2025_update27.aar",
          "size": 149494,
          "sha512": "18cc5370ffa8f47369afbc945c88e0b75a41134396dcf2e5fb193e794d98da77c833b2f3168d9d2a6a7b45188e2de393148c0cc931b61fd3020a50aebda7f8bf",
          "sha256": "1aeb5ff98acee6f757d8d6f60cd0e0c5c4fb9723a6bf8f11b937eaa1a5026a28",
          "sha1": "3324bf18a38b83a649cfa45f86bffec2bdd78e57",
          "md5": "8571b19c0b8a5cf46f993b4d83d2f217"
        }
      ]
    }
  ]
}
