{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.opal",
    "module": "opal-analytics",
    "version": "3.2.6-2025_update26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantMavenApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "opal-analytics-3.2.6-2025_update26.aar",
          "url": "opal-analytics-3.2.6-2025_update26.aar",
          "size": 13531,
          "sha512": "43b16e810c7e73528e121ae2147a099286aa0628a5f02f0ea64dc5303c12948b3d600f1eb64e6dbdc9ea23ba3b1f7205a78e8d308ca9868ea2d036d874a8bb3a",
          "sha256": "7b50f770966ba19ae660ceda73eaffdf16cb27c3428e3b9b132900b0b5917959",
          "sha1": "3bd9c347db0bbc18de38b1f3b39a43c6a17f91d0",
          "md5": "d4b63e5e9af6bac5cfd49d95ceb85e21"
        }
      ]
    },
    {
      "name": "releaseVariantMavenRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "opal-analytics-3.2.6-2025_update26.aar",
          "url": "opal-analytics-3.2.6-2025_update26.aar",
          "size": 13531,
          "sha512": "43b16e810c7e73528e121ae2147a099286aa0628a5f02f0ea64dc5303c12948b3d600f1eb64e6dbdc9ea23ba3b1f7205a78e8d308ca9868ea2d036d874a8bb3a",
          "sha256": "7b50f770966ba19ae660ceda73eaffdf16cb27c3428e3b9b132900b0b5917959",
          "sha1": "3bd9c347db0bbc18de38b1f3b39a43c6a17f91d0",
          "md5": "d4b63e5e9af6bac5cfd49d95ceb85e21"
        }
      ]
    }
  ]
}
