{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.opal",
    "module": "opal-push-fcm",
    "version": "3.2.6-2025_update22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantMavenApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "opal-push-fcm-3.2.6-2025_update22.aar",
          "url": "opal-push-fcm-3.2.6-2025_update22.aar",
          "size": 149499,
          "sha512": "81efe27e56654b9ba2768e4c57302da71d0aad8b6f7f38b69d167e23c518d49d952ccb320555b2e8eca7ef2a889d34c17afb2e1e128886dedfee25e71cdd2ff8",
          "sha256": "1eec2580d16c39c688ef65d896a722a5a8e6460dd9b3a86ef50b2708161b3bf5",
          "sha1": "7df467bbe024df511dbdf651e6c8d62ce9c4a55b",
          "md5": "982f00aaed066f8439314d10bfa74d2a"
        }
      ]
    },
    {
      "name": "releaseVariantMavenRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "opal-push-fcm-3.2.6-2025_update22.aar",
          "url": "opal-push-fcm-3.2.6-2025_update22.aar",
          "size": 149499,
          "sha512": "81efe27e56654b9ba2768e4c57302da71d0aad8b6f7f38b69d167e23c518d49d952ccb320555b2e8eca7ef2a889d34c17afb2e1e128886dedfee25e71cdd2ff8",
          "sha256": "1eec2580d16c39c688ef65d896a722a5a8e6460dd9b3a86ef50b2708161b3bf5",
          "sha1": "7df467bbe024df511dbdf651e6c8d62ce9c4a55b",
          "md5": "982f00aaed066f8439314d10bfa74d2a"
        }
      ]
    }
  ]
}
