{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.opal",
    "module": "opal-core",
    "version": "3.2.6-2025_update25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantMavenApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.8-android"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "24.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "opal-core-3.2.6-2025_update25.aar",
          "url": "opal-core-3.2.6-2025_update25.aar",
          "size": 226292,
          "sha512": "6892afedf1e67adab297560e840b17eb3a80457f88141c05afae8c5bf3ed26f50d35a503c08f1c4df1b4dc5671911ee17304c12ae49a66a3d5cabf0aedcc915d",
          "sha256": "be504a7ff9eb67d63630b101799d411afca79764e0a1eb73e2d24cf7b231703e",
          "sha1": "ff31c1bf24e1db0538e2c5e6385aa07c0a6dd14e",
          "md5": "b15a5f833a9d59e887dd6e2c22416541"
        }
      ]
    },
    {
      "name": "releaseVariantMavenRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.8-android"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "24.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "opal-core-3.2.6-2025_update25.aar",
          "url": "opal-core-3.2.6-2025_update25.aar",
          "size": 226292,
          "sha512": "6892afedf1e67adab297560e840b17eb3a80457f88141c05afae8c5bf3ed26f50d35a503c08f1c4df1b4dc5671911ee17304c12ae49a66a3d5cabf0aedcc915d",
          "sha256": "be504a7ff9eb67d63630b101799d411afca79764e0a1eb73e2d24cf7b231703e",
          "sha1": "ff31c1bf24e1db0538e2c5e6385aa07c0a6dd14e",
          "md5": "b15a5f833a9d59e887dd6e2c22416541"
        }
      ]
    }
  ]
}
