{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.opal",
    "module": "opal-core",
    "version": "3.2.6-2025_update27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantMavenApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.8-android"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "24.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "opal-core-3.2.6-2025_update27.aar",
          "url": "opal-core-3.2.6-2025_update27.aar",
          "size": 226288,
          "sha512": "4978c25e6fd7e9c785d4cfe12a3fac37147a38e29dbed58c4ab9f0bedf7057ed274215c640dc79e07b5c25465acfb8330661692fc93321396383e6fd2f5c650c",
          "sha256": "d6725906c382b8ae361adf0d19251bb1d44bce9b4f7013cedff5f76efee735d1",
          "sha1": "2061fad1195a15ef24ce1d8c02c998fb97d344b0",
          "md5": "b1131c6b023a0079ffa85b93ed06501a"
        }
      ]
    },
    {
      "name": "releaseVariantMavenRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.8-android"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "24.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "opal-core-3.2.6-2025_update27.aar",
          "url": "opal-core-3.2.6-2025_update27.aar",
          "size": 226288,
          "sha512": "4978c25e6fd7e9c785d4cfe12a3fac37147a38e29dbed58c4ab9f0bedf7057ed274215c640dc79e07b5c25465acfb8330661692fc93321396383e6fd2f5c650c",
          "sha256": "d6725906c382b8ae361adf0d19251bb1d44bce9b4f7013cedff5f76efee735d1",
          "sha1": "2061fad1195a15ef24ce1d8c02c998fb97d344b0",
          "md5": "b1131c6b023a0079ffa85b93ed06501a"
        }
      ]
    }
  ]
}
