{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.opal",
    "module": "opal-push-fcm",
    "version": "3.2.6-2025_update20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantMavenApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "opal-push-fcm-3.2.6-2025_update20.aar",
          "url": "opal-push-fcm-3.2.6-2025_update20.aar",
          "size": 149492,
          "sha512": "3bb374996e0cdfc58e9a59042b38c003860ad5b97bf5bdd5c35626f3613a559c9114ccfe789bcb197cc96320469ee941a13f5dbdbd9b894a98cf03e8216045cd",
          "sha256": "cd08ecba7f19db731c5d08352bb5893b14a076310b1825d81053748b3e7ca157",
          "sha1": "3bb56686373595e296a308f313f10304e8efd6e0",
          "md5": "8637443cc82e43e6e564c42569ca648e"
        }
      ]
    },
    {
      "name": "releaseVariantMavenRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "opal-push-fcm-3.2.6-2025_update20.aar",
          "url": "opal-push-fcm-3.2.6-2025_update20.aar",
          "size": 149492,
          "sha512": "3bb374996e0cdfc58e9a59042b38c003860ad5b97bf5bdd5c35626f3613a559c9114ccfe789bcb197cc96320469ee941a13f5dbdbd9b894a98cf03e8216045cd",
          "sha256": "cd08ecba7f19db731c5d08352bb5893b14a076310b1825d81053748b3e7ca157",
          "sha1": "3bb56686373595e296a308f313f10304e8efd6e0",
          "md5": "8637443cc82e43e6e564c42569ca648e"
        }
      ]
    }
  ]
}
